name = "rhracers"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "rhracers"

[env.preview] 
name = "rhracers-preview"