name = "nvsl-swimming-game"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "."

[env.production]
name = "nvsl-swimming-game"

[env.preview]
name = "nvsl-swimming-game-preview"