name = "nvsl-swimming-game"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "echo 'No build step required'"
cwd = "."

[env.production]
name = "nvsl-swimming-game"

[env.preview] 
name = "nvsl-swimming-game-preview"